# Generated by Django 5.2 on 2025-09-19 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_vision', models.CharField(max_length=100)),
                ('c_mission', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_address', models.CharField(max_length=100)),
                ('c_email', models.EmailField(max_length=191, unique=True)),
                ('c_phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('pctid', models.IntegerField(primary_key=True, serialize=False)),
                ('pctname', models.CharField(max_length=100)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='media/productcategory/')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=100)),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='media/products/')),
                ('pcreated', models.DateField(auto_now_add=True)),
                ('pctid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.productcategory')),
            ],
        ),
    ]
