# Generated by Django 5.2 on 2025-07-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('pctid', models.IntegerField(primary_key=True, serialize=False)),
                ('pctname', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField()),
                ('pdesc', models.CharField()),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pimage', models.ImageField(upload_to='')),
                ('pcreated', models.DateField(auto_now_add=True)),
                ('pctid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productcategory')),
            ],
        ),
    ]
