# Generated by Django 5.2 on 2025-09-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='c_mission',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='c_vision',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='c_address',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='c_phone',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='pctname',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdesc',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='products',
            name='pname',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='websiteadmin',
            name='password',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='websiteadmin',
            name='username',
            field=models.CharField(max_length=191, unique=True),
        ),
    ]
