# Generated by Django 5.2 on 2025-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productcategory_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
