# Generated by Django 5.2 on 2025-11-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pprice',
        ),
    ]
