# Generated by Django 5.2 on 2025-11-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_products_pprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pdesc',
            field=models.TextField(),
        ),
    ]
