# Generated by Django 5.2 on 2025-09-17 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_products_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/productcategory/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pctid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.productcategory'),
        ),
    ]
