# Generated by Django 5.2 on 2025-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productcategory_pimage_alter_products_pctid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_vision', models.CharField(max_length=100)),
                ('c_mission', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_address', models.CharField(max_length=200)),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_phone', models.IntegerField(max_length=200)),
            ],
        ),
    ]
