# Generated by Django 5.2 on 2025-09-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aboutinfo_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='c_phone',
            field=models.CharField(max_length=200),
        ),
    ]
